# Generated by Django 3.1.2 on 2020-10-12 19:31

from django.db import migrations, models
import shop_sliders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('re_title', models.CharField(max_length=150, verbose_name='عنوان2')),
                ('link', models.URLField(max_length=150, verbose_name='آدرس')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop_sliders.models.upload_image_path, verbose_name='عکس')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
            },
        ),
    ]
