# Generated by Django 3.1.2 on 2020-10-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_products', '0004_auto_20201010_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('slug', models.SlugField(verbose_name='عنوان در url ')),
                ('timstamp', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('products', models.ManyToManyField(blank=True, to='shop_products.Product', verbose_name='محصولات')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': ' برچسب ها',
            },
        ),
    ]
