# Generated by Django 3.1.2 on 2020-10-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_category', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
