# Generated by Django 3.1.2 on 2020-10-09 18:36

from django.db import migrations, models
import shop_products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('description', models.TextField(max_length=200, verbose_name='توضیحات')),
                ('short_desc', models.CharField(max_length=50, verbose_name='توضیح کوتاه')),
                ('price', models.IntegerField(max_length=20, verbose_name='قیمت')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop_products.models.upload_image_path, verbose_name='عکس')),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
            ],
        ),
    ]
