# Generated by Django 3.1.2 on 2020-10-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
    ]
