# Generated by Django 3.1.2 on 2020-10-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0002_auto_20201009_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='توضیحات'),
        ),
    ]
