# Generated by Django 3.1.2 on 2020-10-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0003_auto_20201009_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
