# Generated by Django 3.1.2 on 2020-10-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_category', '0001_initial'),
        ('shop_products', '0004_auto_20201010_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='shop_category.ProductCategory', verbose_name='دسته بندی ها'),
        ),
    ]
