# Generated by Django 3.1.2 on 2020-10-13 07:20

from django.db import migrations, models
import django.db.models.deletion
import shop_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shop_products.models.upload_galleries_image_path, verbose_name='عکس')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_products.product')),
            ],
        ),
    ]
